server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wzffzm/springcloudstudy.git
          search-paths: config
          username: wzffzm
          password: wz1127002601@sina.com
      label: main